// This file is @generated by prost-build.
/// AhtiEvent is the unified event format for the observability platform
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AhtiEvent {
    /// Identity
    ///
    /// ULID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// Classification
    #[prost(enumeration = "EventType", tag = "3")]
    pub r#type: i32,
    /// e.g., "connection_reset", "oom_kill"
    #[prost(string, tag = "4")]
    pub subtype: ::prost::alloc::string::String,
    #[prost(enumeration = "Severity", tag = "5")]
    pub severity: i32,
    #[prost(enumeration = "Outcome", tag = "6")]
    pub outcome: i32,
    /// Source
    ///
    /// Observer/collector name (tapio, portti, elava)
    #[prost(string, tag = "7")]
    pub source: ::prost::alloc::string::String,
    /// Distributed tracing (optional)
    #[prost(string, tag = "8")]
    pub trace_id: ::prost::alloc::string::String,
    #[prost(string, tag = "9")]
    pub span_id: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub parent_span_id: ::prost::alloc::string::String,
    /// Duration in microseconds
    #[prost(uint64, tag = "11")]
    pub duration_us: u64,
    /// Graph correlation (key for AHTI)
    #[prost(message, repeated, tag = "12")]
    pub entities: ::prost::alloc::vec::Vec<Entity>,
    #[prost(message, repeated, tag = "13")]
    pub relationships: ::prost::alloc::vec::Vec<Relationship>,
    /// Context
    #[prost(string, tag = "14")]
    pub cluster: ::prost::alloc::string::String,
    #[prost(string, tag = "15")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "16")]
    pub labels: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Error details (present when outcome = FAILURE)
    #[prost(message, optional, tag = "17")]
    pub error: ::core::option::Option<EventError>,
    /// Type-specific data (only one populated per event)
    #[prost(oneof = "ahti_event::Data", tags = "20, 21, 22, 23, 24, 25, 26, 27")]
    pub data: ::core::option::Option<ahti_event::Data>,
}
/// Nested message and enum types in `AhtiEvent`.
pub mod ahti_event {
    /// Type-specific data (only one populated per event)
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Data {
        #[prost(message, tag = "20")]
        Network(super::NetworkEventData),
        #[prost(message, tag = "21")]
        Kernel(super::KernelEventData),
        #[prost(message, tag = "22")]
        Container(super::ContainerEventData),
        #[prost(message, tag = "23")]
        K8s(super::K8sEventData),
        #[prost(message, tag = "24")]
        Process(super::ProcessEventData),
        #[prost(message, tag = "25")]
        Resource(super::ResourceEventData),
        /// Prometheus metrics snapshot
        #[prost(message, tag = "26")]
        SignalContext(super::SignalContextEvent),
        /// OpenTelemetry trace data (from OVELA)
        #[prost(message, tag = "27")]
        Otel(super::OTelEventData),
    }
}
/// Entity is a node in the infrastructure graph
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Entity {
    #[prost(enumeration = "EntityType", tag = "1")]
    pub r#type: i32,
    /// UID or unique identifier
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub cluster_id: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub namespace: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "6")]
    pub labels: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Type-specific attributes
    #[prost(map = "string, string", tag = "7")]
    pub attributes: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// MVCC fields
    #[prost(int64, tag = "8")]
    pub generation: i64,
    #[prost(enumeration = "EntityState", tag = "9")]
    pub state: i32,
    #[prost(message, optional, tag = "10")]
    pub deleted_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "11")]
    pub delete_reason: ::prost::alloc::string::String,
}
/// Relationship is an edge in the infrastructure graph
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Relationship {
    #[prost(enumeration = "RelationshipType", tag = "1")]
    pub r#type: i32,
    #[prost(message, optional, tag = "2")]
    pub source: ::core::option::Option<EntityReference>,
    #[prost(message, optional, tag = "3")]
    pub target: ::core::option::Option<EntityReference>,
    #[prost(map = "string, string", tag = "4")]
    pub labels: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// MVCC fields
    #[prost(int64, tag = "5")]
    pub generation: i64,
    #[prost(enumeration = "RelationshipState", tag = "6")]
    pub state: i32,
    #[prost(message, optional, tag = "7")]
    pub deleted_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "8")]
    pub delete_reason: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "9")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EntityReference {
    #[prost(enumeration = "EntityType", tag = "1")]
    pub r#type: i32,
    #[prost(string, tag = "2")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub cluster_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventError {
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "3")]
    pub details: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NetworkEventData {
    /// TCP, UDP, DNS, HTTP, gRPC
    #[prost(string, tag = "1")]
    pub protocol: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub src_ip: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub dst_ip: ::prost::alloc::string::String,
    #[prost(uint32, tag = "4")]
    pub src_port: u32,
    #[prost(uint32, tag = "5")]
    pub dst_port: u32,
    /// inbound, outbound
    #[prost(string, tag = "6")]
    pub direction: ::prost::alloc::string::String,
    /// DNS
    #[prost(string, tag = "7")]
    pub dns_query: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub dns_response: ::prost::alloc::string::String,
    /// HTTP
    #[prost(string, tag = "9")]
    pub http_method: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub http_path: ::prost::alloc::string::String,
    #[prost(int32, tag = "11")]
    pub http_status_code: i32,
    /// Metrics
    #[prost(double, tag = "12")]
    pub latency_ms: f64,
    #[prost(uint64, tag = "13")]
    pub bytes_sent: u64,
    #[prost(uint64, tag = "14")]
    pub bytes_received: u64,
    /// TCP performance
    #[prost(double, tag = "15")]
    pub rtt_baseline_ms: f64,
    #[prost(double, tag = "16")]
    pub rtt_current_ms: f64,
    #[prost(double, tag = "17")]
    pub rtt_degradation_pct: f64,
    #[prost(uint32, tag = "18")]
    pub retransmit_count: u32,
    #[prost(string, tag = "19")]
    pub tcp_state: ::prost::alloc::string::String,
    /// K8s context
    #[prost(string, tag = "20")]
    pub process_name: ::prost::alloc::string::String,
    #[prost(string, tag = "21")]
    pub container_id: ::prost::alloc::string::String,
    #[prost(string, tag = "22")]
    pub pod_name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct KernelEventData {
    /// oom_kill, signal, syscall
    #[prost(string, tag = "1")]
    pub event_type: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub pid: u32,
    #[prost(string, tag = "3")]
    pub command: ::prost::alloc::string::String,
    /// OOM
    #[prost(uint32, tag = "4")]
    pub oom_victim_pid: u32,
    #[prost(string, tag = "5")]
    pub oom_victim_comm: ::prost::alloc::string::String,
    #[prost(uint64, tag = "6")]
    pub memory_requested: u64,
    /// Signals
    #[prost(uint32, tag = "7")]
    pub signal: u32,
    #[prost(uint32, tag = "8")]
    pub signal_code: u32,
    /// Syscalls
    #[prost(uint32, tag = "9")]
    pub syscall_id: u32,
    #[prost(string, tag = "10")]
    pub syscall_name: ::prost::alloc::string::String,
    #[prost(int64, tag = "11")]
    pub syscall_retval: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ContainerEventData {
    #[prost(string, tag = "1")]
    pub container_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub container_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub image: ::prost::alloc::string::String,
    /// running, stopped, crashed
    #[prost(string, tag = "4")]
    pub state: ::prost::alloc::string::String,
    #[prost(int32, tag = "5")]
    pub exit_code: i32,
    #[prost(int32, tag = "6")]
    pub restart_count: i32,
    #[prost(message, optional, tag = "7")]
    pub start_time: ::core::option::Option<::prost_types::Timestamp>,
    /// Resources
    ///
    /// cores
    #[prost(double, tag = "8")]
    pub cpu_usage: f64,
    /// bytes
    #[prost(uint64, tag = "9")]
    pub memory_usage: u64,
    #[prost(uint64, tag = "10")]
    pub memory_limit: u64,
    #[prost(uint64, tag = "11")]
    pub disk_usage: u64,
    /// OOM details
    #[prost(int32, tag = "12")]
    pub signal: i32,
    #[prost(string, tag = "13")]
    pub cgroup_path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct K8sEventData {
    /// Deployment, Pod, Service
    #[prost(string, tag = "1")]
    pub resource_type: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub resource_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub namespace: ::prost::alloc::string::String,
    /// Scheduled, Pulling, Created, Started
    #[prost(string, tag = "4")]
    pub reason: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub message: ::prost::alloc::string::String,
    /// Deployment specifics
    #[prost(int32, tag = "6")]
    pub replicas: i32,
    #[prost(int32, tag = "7")]
    pub ready_replicas: i32,
    #[prost(int32, tag = "8")]
    pub updated_replicas: i32,
    /// progressing, complete, failed
    #[prost(string, tag = "9")]
    pub rollout_status: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ProcessEventData {
    #[prost(uint32, tag = "1")]
    pub pid: u32,
    #[prost(uint32, tag = "2")]
    pub ppid: u32,
    #[prost(string, tag = "3")]
    pub command: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub args: ::prost::alloc::string::String,
    #[prost(uint32, tag = "5")]
    pub uid: u32,
    #[prost(uint32, tag = "6")]
    pub gid: u32,
    #[prost(string, tag = "7")]
    pub user: ::prost::alloc::string::String,
    #[prost(int32, tag = "8")]
    pub exit_code: i32,
    #[prost(message, optional, tag = "9")]
    pub start_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "10")]
    pub end_time: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResourceEventData {
    /// cpu, memory, disk, network
    #[prost(string, tag = "1")]
    pub resource_type: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub node_name: ::prost::alloc::string::String,
    /// CPU
    #[prost(double, tag = "3")]
    pub cpu_usage_pct: f64,
    #[prost(double, tag = "4")]
    pub cpu_throttle_pct: f64,
    /// Memory
    #[prost(uint64, tag = "5")]
    pub memory_used: u64,
    #[prost(uint64, tag = "6")]
    pub memory_available: u64,
    #[prost(double, tag = "7")]
    pub memory_pressure: f64,
    /// Disk
    #[prost(uint64, tag = "8")]
    pub disk_used: u64,
    #[prost(uint64, tag = "9")]
    pub disk_available: u64,
    #[prost(double, tag = "10")]
    pub disk_io_utilization: f64,
}
/// SignalContext contains metric snapshots from Prometheus
/// attached to events for causality analysis.
/// POLKU queries Prometheus when interesting events occur
/// and emits this as a companion event.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalContextEvent {
    /// ID of the event this context belongs to
    #[prost(string, tag = "1")]
    pub linked_event_id: ::prost::alloc::string::String,
    /// When Prometheus was queried
    #[prost(message, optional, tag = "2")]
    pub query_time: ::core::option::Option<::prost_types::Timestamp>,
    /// How far back we looked (e.g., 15min)
    #[prost(message, optional, tag = "3")]
    pub window: ::core::option::Option<::prost_types::Duration>,
    #[prost(message, repeated, tag = "4")]
    pub signals: ::prost::alloc::vec::Vec<SignalSnapshot>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SignalSnapshot {
    /// e.g., "container_cpu_usage_seconds_total"
    #[prost(string, tag = "1")]
    pub metric_name: ::prost::alloc::string::String,
    /// Prometheus labels
    #[prost(map = "string, string", tag = "2")]
    pub labels: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Time series data
    #[prost(message, repeated, tag = "3")]
    pub datapoints: ::prost::alloc::vec::Vec<SignalDataPoint>,
    /// Anomaly detection (optional, computed by POLKU)
    #[prost(bool, tag = "4")]
    pub is_anomaly: bool,
    /// 0.0 - 1.0
    #[prost(double, tag = "5")]
    pub anomaly_score: f64,
    /// spike, drop, trend, deviation
    #[prost(string, tag = "6")]
    pub anomaly_type: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct SignalDataPoint {
    #[prost(message, optional, tag = "1")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(double, tag = "2")]
    pub value: f64,
}
/// OTelEventData contains trace information from sampled spans.
/// OVELA (the tail-sampling OTel Collector) extracts this from interesting
/// traces and converts them to AhtiEvents for causality analysis.
///
/// Use cases:
/// - Correlate slow traces with infrastructure events
/// - Understand what the app was doing during an incident
/// - Trace errors back to their root cause
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OTelEventData {
    /// Service identification
    ///
    /// From resource.service.name
    #[prost(string, tag = "1")]
    pub service_name: ::prost::alloc::string::String,
    /// From resource.service.version
    #[prost(string, tag = "2")]
    pub service_version: ::prost::alloc::string::String,
    /// From resource.service.namespace
    #[prost(string, tag = "3")]
    pub service_namespace: ::prost::alloc::string::String,
    /// Span details
    ///
    /// Span name (e.g., "GET /api/users")
    #[prost(string, tag = "4")]
    pub operation_name: ::prost::alloc::string::String,
    /// CLIENT, SERVER, PRODUCER, CONSUMER, INTERNAL
    #[prost(enumeration = "SpanKind", tag = "5")]
    pub span_kind: i32,
    /// OK, ERROR, UNSET
    #[prost(string, tag = "6")]
    pub status_code: ::prost::alloc::string::String,
    /// Error message if status == ERROR
    #[prost(string, tag = "7")]
    pub status_message: ::prost::alloc::string::String,
    /// Timing
    ///
    /// Span duration in milliseconds
    #[prost(double, tag = "8")]
    pub duration_ms: f64,
    /// HTTP details (if applicable)
    ///
    /// GET, POST, etc.
    #[prost(string, tag = "10")]
    pub http_method: ::prost::alloc::string::String,
    /// Full URL
    #[prost(string, tag = "11")]
    pub http_url: ::prost::alloc::string::String,
    /// Route pattern (e.g., "/users/:id")
    #[prost(string, tag = "12")]
    pub http_route: ::prost::alloc::string::String,
    /// 200, 500, etc.
    #[prost(int32, tag = "13")]
    pub http_status_code: i32,
    /// Database details (if applicable)
    ///
    /// mysql, postgresql, redis, mongodb
    #[prost(string, tag = "20")]
    pub db_system: ::prost::alloc::string::String,
    /// Database name
    #[prost(string, tag = "21")]
    pub db_name: ::prost::alloc::string::String,
    /// SELECT, INSERT, etc.
    #[prost(string, tag = "22")]
    pub db_operation: ::prost::alloc::string::String,
    /// Query (potentially truncated)
    #[prost(string, tag = "23")]
    pub db_statement: ::prost::alloc::string::String,
    /// RPC details (if applicable)
    ///
    /// grpc, thrift, etc.
    #[prost(string, tag = "30")]
    pub rpc_system: ::prost::alloc::string::String,
    /// Service name
    #[prost(string, tag = "31")]
    pub rpc_service: ::prost::alloc::string::String,
    /// Method name
    #[prost(string, tag = "32")]
    pub rpc_method: ::prost::alloc::string::String,
    /// Messaging details (if applicable)
    ///
    /// kafka, rabbitmq, etc.
    #[prost(string, tag = "40")]
    pub messaging_system: ::prost::alloc::string::String,
    /// Topic/queue name
    #[prost(string, tag = "41")]
    pub messaging_destination: ::prost::alloc::string::String,
    /// send, receive, process
    #[prost(string, tag = "42")]
    pub messaging_operation: ::prost::alloc::string::String,
    /// Error details
    ///
    /// Exception class name
    #[prost(string, tag = "50")]
    pub exception_type: ::prost::alloc::string::String,
    /// Exception message
    #[prost(string, tag = "51")]
    pub exception_message: ::prost::alloc::string::String,
    /// Stack trace (potentially truncated)
    #[prost(string, tag = "52")]
    pub exception_stacktrace: ::prost::alloc::string::String,
    /// Why this trace was sampled (set by OVELA)
    ///
    /// error, slow, retry, db_error, server_error
    #[prost(string, tag = "60")]
    pub sample_reason: ::prost::alloc::string::String,
    /// Additional attributes (arbitrary key-value pairs from span)
    #[prost(map = "string, string", tag = "70")]
    pub attributes: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Link to parent span (for causality chaining)
    #[prost(message, repeated, tag = "80")]
    pub links: ::prost::alloc::vec::Vec<SpanLink>,
}
/// SpanLink represents a link to another trace/span
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SpanLink {
    #[prost(string, tag = "1")]
    pub trace_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub span_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub trace_state: ::prost::alloc::string::String,
    #[prost(map = "string, string", tag = "4")]
    pub attributes: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
/// AhtiEventBatch contains multiple events for efficient streaming
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AhtiEventBatch {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<AhtiEvent>,
}
/// AhtiAck acknowledges receipt of events
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AhtiAck {
    /// IDs of successfully received events
    #[prost(string, repeated, tag = "1")]
    pub event_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(bool, tag = "2")]
    pub success: bool,
    /// Error message if success=false
    #[prost(string, tag = "3")]
    pub error: ::prost::alloc::string::String,
}
/// AhtiHealthRequest is the health check request
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct AhtiHealthRequest {}
/// AhtiHealthResponse is the health check response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AhtiHealthResponse {
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    #[prost(string, tag = "2")]
    pub version: ::prost::alloc::string::String,
}
/// Event types (13 base types)
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EventType {
    Unspecified = 0,
    Network = 1,
    Kernel = 2,
    Container = 3,
    Deployment = 4,
    Pod = 5,
    Service = 6,
    Volume = 7,
    Config = 8,
    Health = 9,
    Performance = 10,
    Resource = 11,
    Cluster = 12,
    /// Prometheus metric context
    Signal = 13,
}
impl EventType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EVENT_TYPE_UNSPECIFIED",
            Self::Network => "EVENT_TYPE_NETWORK",
            Self::Kernel => "EVENT_TYPE_KERNEL",
            Self::Container => "EVENT_TYPE_CONTAINER",
            Self::Deployment => "EVENT_TYPE_DEPLOYMENT",
            Self::Pod => "EVENT_TYPE_POD",
            Self::Service => "EVENT_TYPE_SERVICE",
            Self::Volume => "EVENT_TYPE_VOLUME",
            Self::Config => "EVENT_TYPE_CONFIG",
            Self::Health => "EVENT_TYPE_HEALTH",
            Self::Performance => "EVENT_TYPE_PERFORMANCE",
            Self::Resource => "EVENT_TYPE_RESOURCE",
            Self::Cluster => "EVENT_TYPE_CLUSTER",
            Self::Signal => "EVENT_TYPE_SIGNAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EVENT_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "EVENT_TYPE_NETWORK" => Some(Self::Network),
            "EVENT_TYPE_KERNEL" => Some(Self::Kernel),
            "EVENT_TYPE_CONTAINER" => Some(Self::Container),
            "EVENT_TYPE_DEPLOYMENT" => Some(Self::Deployment),
            "EVENT_TYPE_POD" => Some(Self::Pod),
            "EVENT_TYPE_SERVICE" => Some(Self::Service),
            "EVENT_TYPE_VOLUME" => Some(Self::Volume),
            "EVENT_TYPE_CONFIG" => Some(Self::Config),
            "EVENT_TYPE_HEALTH" => Some(Self::Health),
            "EVENT_TYPE_PERFORMANCE" => Some(Self::Performance),
            "EVENT_TYPE_RESOURCE" => Some(Self::Resource),
            "EVENT_TYPE_CLUSTER" => Some(Self::Cluster),
            "EVENT_TYPE_SIGNAL" => Some(Self::Signal),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Severity {
    Unspecified = 0,
    Debug = 1,
    Info = 2,
    Warning = 3,
    Error = 4,
    Critical = 5,
}
impl Severity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SEVERITY_UNSPECIFIED",
            Self::Debug => "SEVERITY_DEBUG",
            Self::Info => "SEVERITY_INFO",
            Self::Warning => "SEVERITY_WARNING",
            Self::Error => "SEVERITY_ERROR",
            Self::Critical => "SEVERITY_CRITICAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SEVERITY_UNSPECIFIED" => Some(Self::Unspecified),
            "SEVERITY_DEBUG" => Some(Self::Debug),
            "SEVERITY_INFO" => Some(Self::Info),
            "SEVERITY_WARNING" => Some(Self::Warning),
            "SEVERITY_ERROR" => Some(Self::Error),
            "SEVERITY_CRITICAL" => Some(Self::Critical),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Outcome {
    Unspecified = 0,
    Success = 1,
    Failure = 2,
    Timeout = 3,
    Unknown = 4,
}
impl Outcome {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OUTCOME_UNSPECIFIED",
            Self::Success => "OUTCOME_SUCCESS",
            Self::Failure => "OUTCOME_FAILURE",
            Self::Timeout => "OUTCOME_TIMEOUT",
            Self::Unknown => "OUTCOME_UNKNOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OUTCOME_UNSPECIFIED" => Some(Self::Unspecified),
            "OUTCOME_SUCCESS" => Some(Self::Success),
            "OUTCOME_FAILURE" => Some(Self::Failure),
            "OUTCOME_TIMEOUT" => Some(Self::Timeout),
            "OUTCOME_UNKNOWN" => Some(Self::Unknown),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EntityType {
    Unspecified = 0,
    Pod = 1,
    Container = 2,
    Node = 3,
    Deployment = 4,
    Statefulset = 5,
    Daemonset = 6,
    Service = 7,
    Endpoint = 8,
    Configmap = 9,
    Secret = 10,
    Pvc = 11,
    Namespace = 12,
}
impl EntityType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ENTITY_TYPE_UNSPECIFIED",
            Self::Pod => "ENTITY_TYPE_POD",
            Self::Container => "ENTITY_TYPE_CONTAINER",
            Self::Node => "ENTITY_TYPE_NODE",
            Self::Deployment => "ENTITY_TYPE_DEPLOYMENT",
            Self::Statefulset => "ENTITY_TYPE_STATEFULSET",
            Self::Daemonset => "ENTITY_TYPE_DAEMONSET",
            Self::Service => "ENTITY_TYPE_SERVICE",
            Self::Endpoint => "ENTITY_TYPE_ENDPOINT",
            Self::Configmap => "ENTITY_TYPE_CONFIGMAP",
            Self::Secret => "ENTITY_TYPE_SECRET",
            Self::Pvc => "ENTITY_TYPE_PVC",
            Self::Namespace => "ENTITY_TYPE_NAMESPACE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ENTITY_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "ENTITY_TYPE_POD" => Some(Self::Pod),
            "ENTITY_TYPE_CONTAINER" => Some(Self::Container),
            "ENTITY_TYPE_NODE" => Some(Self::Node),
            "ENTITY_TYPE_DEPLOYMENT" => Some(Self::Deployment),
            "ENTITY_TYPE_STATEFULSET" => Some(Self::Statefulset),
            "ENTITY_TYPE_DAEMONSET" => Some(Self::Daemonset),
            "ENTITY_TYPE_SERVICE" => Some(Self::Service),
            "ENTITY_TYPE_ENDPOINT" => Some(Self::Endpoint),
            "ENTITY_TYPE_CONFIGMAP" => Some(Self::Configmap),
            "ENTITY_TYPE_SECRET" => Some(Self::Secret),
            "ENTITY_TYPE_PVC" => Some(Self::Pvc),
            "ENTITY_TYPE_NAMESPACE" => Some(Self::Namespace),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EntityState {
    Unspecified = 0,
    Active = 1,
    Deleted = 2,
}
impl EntityState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ENTITY_STATE_UNSPECIFIED",
            Self::Active => "ENTITY_STATE_ACTIVE",
            Self::Deleted => "ENTITY_STATE_DELETED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ENTITY_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "ENTITY_STATE_ACTIVE" => Some(Self::Active),
            "ENTITY_STATE_DELETED" => Some(Self::Deleted),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RelationshipType {
    Unspecified = 0,
    ConnectsTo = 1,
    DependsOn = 2,
    Owns = 3,
    Exposes = 4,
    Mounts = 5,
    ScheduledOn = 6,
    Manages = 7,
    Uses = 8,
    Causes = 9,
}
impl RelationshipType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "RELATIONSHIP_TYPE_UNSPECIFIED",
            Self::ConnectsTo => "RELATIONSHIP_TYPE_CONNECTS_TO",
            Self::DependsOn => "RELATIONSHIP_TYPE_DEPENDS_ON",
            Self::Owns => "RELATIONSHIP_TYPE_OWNS",
            Self::Exposes => "RELATIONSHIP_TYPE_EXPOSES",
            Self::Mounts => "RELATIONSHIP_TYPE_MOUNTS",
            Self::ScheduledOn => "RELATIONSHIP_TYPE_SCHEDULED_ON",
            Self::Manages => "RELATIONSHIP_TYPE_MANAGES",
            Self::Uses => "RELATIONSHIP_TYPE_USES",
            Self::Causes => "RELATIONSHIP_TYPE_CAUSES",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RELATIONSHIP_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "RELATIONSHIP_TYPE_CONNECTS_TO" => Some(Self::ConnectsTo),
            "RELATIONSHIP_TYPE_DEPENDS_ON" => Some(Self::DependsOn),
            "RELATIONSHIP_TYPE_OWNS" => Some(Self::Owns),
            "RELATIONSHIP_TYPE_EXPOSES" => Some(Self::Exposes),
            "RELATIONSHIP_TYPE_MOUNTS" => Some(Self::Mounts),
            "RELATIONSHIP_TYPE_SCHEDULED_ON" => Some(Self::ScheduledOn),
            "RELATIONSHIP_TYPE_MANAGES" => Some(Self::Manages),
            "RELATIONSHIP_TYPE_USES" => Some(Self::Uses),
            "RELATIONSHIP_TYPE_CAUSES" => Some(Self::Causes),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RelationshipState {
    Unspecified = 0,
    Active = 1,
    Deleted = 2,
}
impl RelationshipState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "RELATIONSHIP_STATE_UNSPECIFIED",
            Self::Active => "RELATIONSHIP_STATE_ACTIVE",
            Self::Deleted => "RELATIONSHIP_STATE_DELETED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RELATIONSHIP_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "RELATIONSHIP_STATE_ACTIVE" => Some(Self::Active),
            "RELATIONSHIP_STATE_DELETED" => Some(Self::Deleted),
            _ => None,
        }
    }
}
/// SpanKind mirrors OTel's SpanKind enum
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SpanKind {
    Unspecified = 0,
    Internal = 1,
    Server = 2,
    Client = 3,
    Producer = 4,
    Consumer = 5,
}
impl SpanKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SPAN_KIND_UNSPECIFIED",
            Self::Internal => "SPAN_KIND_INTERNAL",
            Self::Server => "SPAN_KIND_SERVER",
            Self::Client => "SPAN_KIND_CLIENT",
            Self::Producer => "SPAN_KIND_PRODUCER",
            Self::Consumer => "SPAN_KIND_CONSUMER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SPAN_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "SPAN_KIND_INTERNAL" => Some(Self::Internal),
            "SPAN_KIND_SERVER" => Some(Self::Server),
            "SPAN_KIND_CLIENT" => Some(Self::Client),
            "SPAN_KIND_PRODUCER" => Some(Self::Producer),
            "SPAN_KIND_CONSUMER" => Some(Self::Consumer),
            _ => None,
        }
    }
}
/// Generated client implementations.
pub mod ahti_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    /// AhtiService receives events from POLKU gateway
    #[derive(Debug, Clone)]
    pub struct AhtiServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AhtiServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AhtiServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::BoxBody>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AhtiServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::BoxBody>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::BoxBody>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AhtiServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// SendEvent sends a single event to AHTI
        pub async fn send_event(
            &mut self,
            request: impl tonic::IntoRequest<super::AhtiEvent>,
        ) -> std::result::Result<tonic::Response<super::AhtiAck>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ahti.v1.AhtiService/SendEvent",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ahti.v1.AhtiService", "SendEvent"));
            self.inner.unary(req, path, codec).await
        }
        /// StreamEvents streams batches of events to AHTI
        pub async fn stream_events(
            &mut self,
            request: impl tonic::IntoStreamingRequest<Message = super::AhtiEventBatch>,
        ) -> std::result::Result<
            tonic::Response<tonic::codec::Streaming<super::AhtiAck>>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ahti.v1.AhtiService/StreamEvents",
            );
            let mut req = request.into_streaming_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ahti.v1.AhtiService", "StreamEvents"));
            self.inner.streaming(req, path, codec).await
        }
        /// Health check
        pub async fn health(
            &mut self,
            request: impl tonic::IntoRequest<super::AhtiHealthRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AhtiHealthResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/ahti.v1.AhtiService/Health",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("ahti.v1.AhtiService", "Health"));
            self.inner.unary(req, path, codec).await
        }
    }
}
/// Generated server implementations.
pub mod ahti_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AhtiServiceServer.
    #[async_trait]
    pub trait AhtiService: std::marker::Send + std::marker::Sync + 'static {
        /// SendEvent sends a single event to AHTI
        async fn send_event(
            &self,
            request: tonic::Request<super::AhtiEvent>,
        ) -> std::result::Result<tonic::Response<super::AhtiAck>, tonic::Status>;
        /// Server streaming response type for the StreamEvents method.
        type StreamEventsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::AhtiAck, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// StreamEvents streams batches of events to AHTI
        async fn stream_events(
            &self,
            request: tonic::Request<tonic::Streaming<super::AhtiEventBatch>>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamEventsStream>,
            tonic::Status,
        >;
        /// Health check
        async fn health(
            &self,
            request: tonic::Request<super::AhtiHealthRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AhtiHealthResponse>,
            tonic::Status,
        >;
    }
    /// AhtiService receives events from POLKU gateway
    #[derive(Debug)]
    pub struct AhtiServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AhtiServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AhtiServiceServer<T>
    where
        T: AhtiService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/ahti.v1.AhtiService/SendEvent" => {
                    #[allow(non_camel_case_types)]
                    struct SendEventSvc<T: AhtiService>(pub Arc<T>);
                    impl<T: AhtiService> tonic::server::UnaryService<super::AhtiEvent>
                    for SendEventSvc<T> {
                        type Response = super::AhtiAck;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AhtiEvent>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AhtiService>::send_event(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SendEventSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ahti.v1.AhtiService/StreamEvents" => {
                    #[allow(non_camel_case_types)]
                    struct StreamEventsSvc<T: AhtiService>(pub Arc<T>);
                    impl<
                        T: AhtiService,
                    > tonic::server::StreamingService<super::AhtiEventBatch>
                    for StreamEventsSvc<T> {
                        type Response = super::AhtiAck;
                        type ResponseStream = T::StreamEventsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::AhtiEventBatch>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AhtiService>::stream_events(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamEventsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/ahti.v1.AhtiService/Health" => {
                    #[allow(non_camel_case_types)]
                    struct HealthSvc<T: AhtiService>(pub Arc<T>);
                    impl<
                        T: AhtiService,
                    > tonic::server::UnaryService<super::AhtiHealthRequest>
                    for HealthSvc<T> {
                        type Response = super::AhtiHealthResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AhtiHealthRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AhtiService>::health(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AhtiServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "ahti.v1.AhtiService";
    impl<T> tonic::server::NamedService for AhtiServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
