// This file is @generated by prost-build.
/// Event is POLKU's wire-format envelope for gRPC boundaries.
///
/// Events are converted to/from `Message` at ingest/emit boundaries.
/// The pipeline itself uses `Message` exclusively.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    /// Unique event ID (ULID recommended)
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Unix timestamp in nanoseconds
    #[prost(int64, tag = "2")]
    pub timestamp_unix_ns: i64,
    /// Source that produced this event
    #[prost(string, tag = "3")]
    pub source: ::prost::alloc::string::String,
    /// User-defined event type
    #[prost(string, tag = "4")]
    pub event_type: ::prost::alloc::string::String,
    /// Arbitrary key-value metadata
    #[prost(map = "string, string", tag = "5")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Opaque payload bytes
    #[prost(bytes = "vec", tag = "6")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// Optional routing hints for Emitters
    #[prost(string, repeated, tag = "7")]
    pub route_to: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Classification
    #[prost(enumeration = "Severity", tag = "10")]
    pub severity: i32,
    #[prost(enumeration = "Outcome", tag = "11")]
    pub outcome: i32,
}
/// Severity indicates the importance/urgency of an event
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Severity {
    Unspecified = 0,
    Debug = 1,
    Info = 2,
    Warning = 3,
    Error = 4,
    Critical = 5,
}
impl Severity {
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SEVERITY_UNSPECIFIED",
            Self::Debug => "SEVERITY_DEBUG",
            Self::Info => "SEVERITY_INFO",
            Self::Warning => "SEVERITY_WARNING",
            Self::Error => "SEVERITY_ERROR",
            Self::Critical => "SEVERITY_CRITICAL",
        }
    }
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SEVERITY_UNSPECIFIED" => Some(Self::Unspecified),
            "SEVERITY_DEBUG" => Some(Self::Debug),
            "SEVERITY_INFO" => Some(Self::Info),
            "SEVERITY_WARNING" => Some(Self::Warning),
            "SEVERITY_ERROR" => Some(Self::Error),
            "SEVERITY_CRITICAL" => Some(Self::Critical),
            _ => None,
        }
    }
}
/// Outcome indicates the result of an operation
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Outcome {
    Unspecified = 0,
    Success = 1,
    Failure = 2,
    Timeout = 3,
    Unknown = 4,
}
impl Outcome {
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OUTCOME_UNSPECIFIED",
            Self::Success => "OUTCOME_SUCCESS",
            Self::Failure => "OUTCOME_FAILURE",
            Self::Timeout => "OUTCOME_TIMEOUT",
            Self::Unknown => "OUTCOME_UNKNOWN",
        }
    }
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OUTCOME_UNSPECIFIED" => Some(Self::Unspecified),
            "OUTCOME_SUCCESS" => Some(Self::Success),
            "OUTCOME_FAILURE" => Some(Self::Failure),
            "OUTCOME_TIMEOUT" => Some(Self::Timeout),
            "OUTCOME_UNKNOWN" => Some(Self::Unknown),
            _ => None,
        }
    }
}
