// This file is @generated by prost-build.
/// Event is POLKU's wire-format envelope for gRPC boundaries.
///
/// Events are converted to/from Message at ingest/emit boundaries.
/// The pipeline itself uses Message exclusively.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Event {
    /// Unique event ID (ULID recommended)
    ///
    /// Should be globally unique. If not provided, POLKU will generate one.
    /// ULIDs are preferred as they're sortable by time.
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Unix timestamp in nanoseconds
    ///
    /// When the event occurred, not when it was received.
    /// If not provided, POLKU will set it to the current time.
    #[prost(int64, tag = "2")]
    pub timestamp_unix_ns: i64,
    /// Source that produced this event
    ///
    /// Identifies the origin of the event (e.g., "tapio", "portti", "elava").
    /// Used for routing and filtering.
    #[prost(string, tag = "3")]
    pub source: ::prost::alloc::string::String,
    /// User-defined event type
    ///
    /// A hierarchical type identifier (e.g., "network.connection", "k8s.pod.created").
    /// Used for routing, filtering, and transformation.
    #[prost(string, tag = "4")]
    pub event_type: ::prost::alloc::string::String,
    /// Arbitrary key-value metadata
    ///
    /// Additional context about the event that doesn't belong in the payload.
    /// Common keys: "cluster", "namespace", "trace_id", "span_id"
    #[prost(map = "string, string", tag = "5")]
    pub metadata: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// Opaque payload bytes
    ///
    /// Can be any format: JSON, protobuf, msgpack, etc.
    /// Emitters must parse based on event_type.
    #[prost(bytes = "vec", tag = "6")]
    pub payload: ::prost::alloc::vec::Vec<u8>,
    /// Optional routing hints for Emitters
    ///
    /// If non-empty, only emitters with matching names will receive this event.
    /// If empty, all emitters receive the event (fan-out).
    #[prost(string, repeated, tag = "7")]
    pub route_to: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Classification
    #[prost(enumeration = "Severity", tag = "10")]
    pub severity: i32,
    #[prost(enumeration = "Outcome", tag = "11")]
    pub outcome: i32,
}
/// Severity indicates the importance/urgency of an event
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Severity {
    Unspecified = 0,
    Debug = 1,
    Info = 2,
    Warning = 3,
    Error = 4,
    Critical = 5,
}
impl Severity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SEVERITY_UNSPECIFIED",
            Self::Debug => "SEVERITY_DEBUG",
            Self::Info => "SEVERITY_INFO",
            Self::Warning => "SEVERITY_WARNING",
            Self::Error => "SEVERITY_ERROR",
            Self::Critical => "SEVERITY_CRITICAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SEVERITY_UNSPECIFIED" => Some(Self::Unspecified),
            "SEVERITY_DEBUG" => Some(Self::Debug),
            "SEVERITY_INFO" => Some(Self::Info),
            "SEVERITY_WARNING" => Some(Self::Warning),
            "SEVERITY_ERROR" => Some(Self::Error),
            "SEVERITY_CRITICAL" => Some(Self::Critical),
            _ => None,
        }
    }
}
/// Outcome indicates the result of an operation
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Outcome {
    Unspecified = 0,
    Success = 1,
    Failure = 2,
    Timeout = 3,
    Unknown = 4,
}
impl Outcome {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OUTCOME_UNSPECIFIED",
            Self::Success => "OUTCOME_SUCCESS",
            Self::Failure => "OUTCOME_FAILURE",
            Self::Timeout => "OUTCOME_TIMEOUT",
            Self::Unknown => "OUTCOME_UNKNOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OUTCOME_UNSPECIFIED" => Some(Self::Unspecified),
            "OUTCOME_SUCCESS" => Some(Self::Success),
            "OUTCOME_FAILURE" => Some(Self::Failure),
            "OUTCOME_TIMEOUT" => Some(Self::Timeout),
            "OUTCOME_UNKNOWN" => Some(Self::Unknown),
            _ => None,
        }
    }
}
