// This file is @generated by prost-build.
/// Batch of events for streaming ingestion
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestBatch {
    /// Source identifier (e.g., "my-agent", "otel-collector")
    #[prost(string, tag = "1")]
    pub source: ::prost::alloc::string::String,
    /// Cluster/environment identifier
    #[prost(string, tag = "2")]
    pub cluster: ::prost::alloc::string::String,
    /// Either raw bytes (needs plugin transformation) or pre-formatted events
    #[prost(oneof = "ingest_batch::Payload", tags = "3, 4")]
    pub payload: ::core::option::Option<ingest_batch::Payload>,
}
/// Nested message and enum types in `IngestBatch`.
pub mod ingest_batch {
    /// Either raw bytes (needs plugin transformation) or pre-formatted events
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag = "3")]
        Raw(super::RawPayload),
        #[prost(message, tag = "4")]
        Events(super::EventPayload),
    }
}
/// Raw bytes payload - requires InputPlugin transformation
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RawPayload {
    /// Serialized source-specific format
    #[prost(bytes = "vec", tag = "1")]
    pub data: ::prost::alloc::vec::Vec<u8>,
    /// Format hint: "protobuf", "json", "msgpack", etc.
    #[prost(string, tag = "2")]
    pub format: ::prost::alloc::string::String,
}
/// Pre-formatted events - pass-through mode (no transformation)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct EventPayload {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<::polku_core::Event>,
}
/// Single event for unary ingestion
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IngestEvent {
    #[prost(string, tag = "1")]
    pub source: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub cluster: ::prost::alloc::string::String,
    /// Format hint for raw payload
    #[prost(string, tag = "5")]
    pub format: ::prost::alloc::string::String,
    #[prost(oneof = "ingest_event::Payload", tags = "3, 4")]
    pub payload: ::core::option::Option<ingest_event::Payload>,
}
/// Nested message and enum types in `IngestEvent`.
pub mod ingest_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        /// Raw bytes (needs transformation)
        #[prost(bytes, tag = "3")]
        Raw(::prost::alloc::vec::Vec<u8>),
        /// Pre-formatted event (pass-through)
        #[prost(message, tag = "4")]
        Event(::polku_core::Event),
    }
}
/// Acknowledgment response
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Ack {
    /// Successfully processed event IDs
    #[prost(string, repeated, tag = "1")]
    pub event_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Errors for failed events
    #[prost(message, repeated, tag = "2")]
    pub errors: ::prost::alloc::vec::Vec<AckError>,
    /// Current buffer size (for backpressure)
    #[prost(int64, tag = "3")]
    pub buffer_size: i64,
    /// Max buffer capacity
    #[prost(int64, tag = "4")]
    pub buffer_capacity: i64,
    /// Middleware drop statistics (helps clients understand WHY events aren't processed)
    /// These are cumulative counts since connection start.
    #[prost(message, optional, tag = "5")]
    pub middleware_stats: ::core::option::Option<MiddlewareStats>,
}
/// MiddlewareStats provides visibility into the middleware pipeline.
/// Clients can use this to distinguish between:
///    - Backpressure (buffer full) → slow down, events will be processed
///    - Rate limiting → you're sending too fast, events are dropped
///    - Sampling → intentional drops by policy, expected behavior
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MiddlewareStats {
    /// Rate limiter drops (client exceeding allowed rate)
    #[prost(int64, tag = "1")]
    pub rate_limited_count: i64,
    /// Sampler drops (intentional sampling, e.g., 10% of network events)
    #[prost(int64, tag = "2")]
    pub sampled_out_count: i64,
    /// Dedup drops (duplicate event IDs within window)
    #[prost(int64, tag = "3")]
    pub dedup_count: i64,
    /// Filter drops (events filtered by CEL rules)
    #[prost(int64, tag = "4")]
    pub filtered_count: i64,
    /// Buffer full drops (backpressure overflow)
    #[prost(int64, tag = "5")]
    pub buffer_overflow_count: i64,
    /// Total events received (before any middleware)
    #[prost(int64, tag = "6")]
    pub total_received: i64,
    /// Total events forwarded (after all middleware)
    #[prost(int64, tag = "7")]
    pub total_forwarded: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AckError {
    #[prost(string, tag = "1")]
    pub event_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// Health check
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HealthRequest {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HealthResponse {
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    #[prost(map = "string, message", tag = "2")]
    pub components: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ComponentHealth,
    >,
    #[prost(int64, tag = "3")]
    pub uptime_seconds: i64,
    #[prost(uint64, tag = "4")]
    pub events_processed: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ComponentHealth {
    #[prost(bool, tag = "1")]
    pub healthy: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// K8s event from PORTTI (matches portti/pkg/proto format)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct K8sEvent {
    /// Event ID (ULID)
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Unix timestamp in nanoseconds
    #[prost(int64, tag = "2")]
    pub timestamp_unix_nano: i64,
    /// Resource type: deployment, pod, service, etc.
    #[prost(string, tag = "3")]
    pub resource: ::prost::alloc::string::String,
    /// Action: create, update, delete
    #[prost(string, tag = "4")]
    pub action: ::prost::alloc::string::String,
    /// K8s namespace
    #[prost(string, tag = "5")]
    pub namespace: ::prost::alloc::string::String,
    /// Resource name
    #[prost(string, tag = "6")]
    pub name: ::prost::alloc::string::String,
    /// JSON-encoded K8s object
    #[prost(bytes = "vec", tag = "7")]
    pub object: ::prost::alloc::vec::Vec<u8>,
    /// For updates (previous state)
    #[prost(bytes = "vec", tag = "8")]
    pub old_object: ::prost::alloc::vec::Vec<u8>,
    /// Cluster identifier
    #[prost(string, tag = "9")]
    pub cluster_id: ::prost::alloc::string::String,
}
/// Batch of K8s events for streaming
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct K8sEventBatch {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<K8sEvent>,
    #[prost(string, tag = "2")]
    pub cluster_id: ::prost::alloc::string::String,
}
/// Simple response for unary RPCs
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// Error message if success=false
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
}
/// Generated server implementations.
pub mod gateway_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with GatewayServer.
    #[async_trait]
    pub trait Gateway: std::marker::Send + std::marker::Sync + 'static {
        /// Server streaming response type for the StreamEvents method.
        type StreamEventsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::Ack, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Bidirectional streaming for high-throughput event ingestion
        async fn stream_events(
            &self,
            request: tonic::Request<tonic::Streaming<super::IngestBatch>>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamEventsStream>,
            tonic::Status,
        >;
        /// Unary RPC for single event submission
        async fn send_event(
            &self,
            request: tonic::Request<super::IngestEvent>,
        ) -> std::result::Result<tonic::Response<super::Ack>, tonic::Status>;
        /// Health check endpoint
        async fn health(
            &self,
            request: tonic::Request<super::HealthRequest>,
        ) -> std::result::Result<tonic::Response<super::HealthResponse>, tonic::Status>;
    }
    /// Gateway service - the main entry point for event ingestion
    #[derive(Debug)]
    pub struct GatewayServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> GatewayServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for GatewayServer<T>
    where
        T: Gateway,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/polku.v1.Gateway/StreamEvents" => {
                    #[allow(non_camel_case_types)]
                    struct StreamEventsSvc<T: Gateway>(pub Arc<T>);
                    impl<T: Gateway> tonic::server::StreamingService<super::IngestBatch>
                    for StreamEventsSvc<T> {
                        type Response = super::Ack;
                        type ResponseStream = T::StreamEventsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<tonic::Streaming<super::IngestBatch>>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Gateway>::stream_events(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamEventsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/polku.v1.Gateway/SendEvent" => {
                    #[allow(non_camel_case_types)]
                    struct SendEventSvc<T: Gateway>(pub Arc<T>);
                    impl<T: Gateway> tonic::server::UnaryService<super::IngestEvent>
                    for SendEventSvc<T> {
                        type Response = super::Ack;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::IngestEvent>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Gateway>::send_event(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SendEventSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/polku.v1.Gateway/Health" => {
                    #[allow(non_camel_case_types)]
                    struct HealthSvc<T: Gateway>(pub Arc<T>);
                    impl<T: Gateway> tonic::server::UnaryService<super::HealthRequest>
                    for HealthSvc<T> {
                        type Response = super::HealthResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::HealthRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as Gateway>::health(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = HealthSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for GatewayServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "polku.v1.Gateway";
    impl<T> tonic::server::NamedService for GatewayServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
/// Generated server implementations.
pub mod portti_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with PorttiServiceServer.
    #[async_trait]
    pub trait PorttiService: std::marker::Send + std::marker::Sync + 'static {
        /// Send a single K8s event
        async fn send_k8s_event(
            &self,
            request: tonic::Request<super::K8sEvent>,
        ) -> std::result::Result<tonic::Response<super::SendResponse>, tonic::Status>;
        /// Server streaming response type for the StreamK8sEvents method.
        type StreamK8sEventsStream: tonic::codegen::tokio_stream::Stream<
                Item = std::result::Result<super::Ack, tonic::Status>,
            >
            + std::marker::Send
            + 'static;
        /// Stream K8s events for high-throughput ingestion
        async fn stream_k8s_events(
            &self,
            request: tonic::Request<tonic::Streaming<super::K8sEventBatch>>,
        ) -> std::result::Result<
            tonic::Response<Self::StreamK8sEventsStream>,
            tonic::Status,
        >;
    }
    /// PorttiService receives K8s events from PORTTI collectors
    #[derive(Debug)]
    pub struct PorttiServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> PorttiServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for PorttiServiceServer<T>
    where
        T: PorttiService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::BoxBody>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/polku.v1.PorttiService/SendK8sEvent" => {
                    #[allow(non_camel_case_types)]
                    struct SendK8sEventSvc<T: PorttiService>(pub Arc<T>);
                    impl<T: PorttiService> tonic::server::UnaryService<super::K8sEvent>
                    for SendK8sEventSvc<T> {
                        type Response = super::SendResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::K8sEvent>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PorttiService>::send_k8s_event(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = SendK8sEventSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/polku.v1.PorttiService/StreamK8sEvents" => {
                    #[allow(non_camel_case_types)]
                    struct StreamK8sEventsSvc<T: PorttiService>(pub Arc<T>);
                    impl<
                        T: PorttiService,
                    > tonic::server::StreamingService<super::K8sEventBatch>
                    for StreamK8sEventsSvc<T> {
                        type Response = super::Ack;
                        type ResponseStream = T::StreamK8sEventsStream;
                        type Future = BoxFuture<
                            tonic::Response<Self::ResponseStream>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                tonic::Streaming<super::K8sEventBatch>,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as PorttiService>::stream_k8s_events(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StreamK8sEventsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.streaming(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(empty_body());
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for PorttiServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "polku.v1.PorttiService";
    impl<T> tonic::server::NamedService for PorttiServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
